### PR TITLE
add cros detection (again)

### PR DESCRIPTION
**Pull request by MrBrain295**
see #5

### CODE REVIEW

**Comment by TheSpiritOfDark** [comment]
cool

**Comment by osama828484848484** [comment]
Ubisoft goes Steamworks bye bye, always on DRM

**Comment by osama828484848484** [comment]
Ubisoft goes Steamworks bye bye, always on DRM

**Comment by osama828484848484** [comment]
Ubisoft goes Steamworks bye bye, always on DRM

**Comment by osama828484848484** [comment]
Ubisoft goes Steamworks bye bye, always on DRM

**Comment by osama828484848484** [comment]
Ubisoft goes Steamworks bye bye, always on DRM

**Comment by osama828484848484** [comment]
Ubisoft goes Steamworks bye bye, always on DRM

**Comment by MrBrain295** [comment]
@TheSpiritOfDark @legoskid @chrossystem osama is back

**Comment by chrossystem** [comment]
We know, he's going insane

**Comment by legoskid** [comment]
> @TheSpiritOfDark @legoskid @chrossystem osama is back

I like watching

**Pull request merged**
