### PR TITLE
check for cros

### PR DESCRIPTION
**Pull request by MrBrain295**
i dont have a chromebook to test this on but it did stop on my computer so i think its good

### CODE REVIEW

**Comment by TheSpiritOfDark** [comment]
Sorry, it errors out if your not on cros, gsctool Shouldn't exist and even if it does it'll fail to contact the cr50

**Comment by MrBrain295** [comment]
weird

**Comment by TheSpiritOfDark** [comment]
Correct me if I'm wrong but this is unnecessary

**Comment by MrBrain295** [comment]
i wanted it to fail if ur not on cros bc its usless then right

**Comment by MrBrain295** [comment]
it was to make sure people dont waste computing time trying to find codes of there not on cros

**Comment by MrBrain295** [comment]
> Correct me if I'm wrong but this is unnecessary

it is kinda

**Comment by TheSpiritOfDark** [comment]
Yeah its useless if your not on cros, but if your not on cros it'll throw a bunch of errors

**Comment by MrBrain295** [comment]
wdym

**Comment by TheSpiritOfDark** [comment]
Does the script work on your PC without this?

**Comment by TheSpiritOfDark** [comment]
I haven't tried it honestly but I assume it wouldn't

**Comment by MrBrain295** [comment]
it runs but cant acctually check anything so its useless

**Comment by MrBrain295** [comment]
but with this it just cleanly exits

**Comment by TheSpiritOfDark** [comment]
So it doesn't error out, and tries bruteforcing on a normal machine?

**Comment by MrBrain295** [comment]
yeah

**Comment by TheSpiritOfDark** [comment]
Weird

**Comment by MrBrain295** [comment]
like there are errors but it keeps running and is so fast u cant see them

**Comment by TheSpiritOfDark** [comment]
Oh, there's definitely cleaner ways to do this and you should probably have it check for gsctool or the cr50 instead of that file

**Comment by MrBrain295** [comment]
ok

**Comment by MrBrain295** [comment]
ill fix

**Comment by TheSpiritOfDark** [comment]
Okay

**Comment by MrBrain295** [comment]
ok i fixed it

**Comment by TheSpiritOfDark** [comment]
This is Better, but I think we should have the primary function defined as main so we can easily call it without having to put the whole thing in an if statement

**Comment by TheSpiritOfDark** [comment]
That'll just make life easier in the future

**Comment by MrBrain295** [comment]
ok

**Comment by MrBrain295** [comment]
like this?

**Comment by TheSpiritOfDark** [comment]
I gotta get on my PC to actually read this

**Comment by MrBrain295** [comment]
ok

**Comment by TheSpiritOfDark** [comment]
looks good

**Comment by TheSpiritOfDark** [comment]
wrong button

**Comment by legoskid** [comment]
> wrong button

bruh

**Comment by TheSpiritOfDark** [comment]
lmao

**Pull request merged**
