### PR TITLE
Updated code

### PR DESCRIPTION
**Pull request by localuser-isback**
image

### CODE REVIEW

**Comment by localuser-isback** [comment]
Includes some optimizations & multi-instance

**Comment by TheSpiritOfDark** [comment]
it generates 1000 codes really fast
should probably up that

**Comment by localuser-isback** [comment]
updated to 10000

**Comment by TheSpiritOfDark** [comment]
the total possible code count is 2.8 trillion, or 36^8. take what you will from that

**Comment by chrossystem** [comment]
possible every 100,000 codes or 1,000,000 codes
or prompt the user at the start

**Comment by localuser-isback** [comment]
yall have an option to print every time there was a code generated

**Comment by TheSpiritOfDark** [comment]
this looks fine

**Review by chrossystem — APPROVED** [review]
merge it :fire: :fire:

**Comment by osama855858585** [comment]
does the same thing as my pr but is merged, but when i make the pr i get told to kill myself & get blocked from org removing my contributions, average tn skids

image
image

**Comment by chrossystem** [comment]
image
image

**Comment by chrossystem** [comment]
oops, same image twice

**Comment by osama855858585** [comment]
(edited)
image

**Comment by osama855858585** [comment]
image
bro is NOT telling the truth 😭 😭

**Comment by TheSpiritOfDark** [comment]
apologe

**Comment by chrossystem** [comment]
image

**Comment by TheSpiritOfDark** [comment]
lol

**Comment by chrossystem** [comment]
Least obvious osama alt :sob:

**Comment by osama855858585** [comment]
not telling the truth again, "that was not acceptable for me at all to say" 🤓 still denied a pr which does the same this one does & removed me from contributions

**Comment by osama855858585** [comment]
read my name ofc its my alt are you dumb

**Comment by chrossystem** [comment]
you didnt contribute a damn thing, your name was only in there because you had added a thing that i coded and had told you that you can add it

**Comment by osama855858585** [comment]
i told you i was going to add it, you said "no wait for me to write it then you contribute it"

**Comment by osama855858585** [comment]
+ you're ignoring the fact this pr is the exact same thing as mine but you denied mine

**Comment by chrossystem** [comment]
duh

**Comment by TheSpiritOfDark** [comment]
sorry about that

**Comment by osama828484848484** [comment]
the glaze to keep blocking me, LOL
you're a skid group, rafall soon, Ubisoft goes Steamworks bye bye, always on DRM

**Comment by osama828484848484** [comment]
Ubisoft goes Steamworks bye bye, always on DRM

**Comment by osama828484848484** [comment]
Ubisoft goes Steamworks bye bye, always on DRM

**Comment by osama828484848484** [comment]
Ubisoft goes Steamworks bye bye, always on DRM

**Comment by osama828484848484** [comment]
Ubisoft goes Steamworks bye bye, always on DRM

**Comment by osama828484848484** [comment]
Ubisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRMUbisoft goes Steamworks bye bye, always on DRM

**Comment by chrossystem** [comment]
Bro is going insane 🗣️

**Comment by TheSpiritOfDark** [comment]
osama stfu challenge (impossible)

**Comment by chrossystem** [comment]
Real

**Comment by TheSpiritOfDark** [comment]
not so impossible now eh?

**Pull request merged**
