### PR TITLE
make it better.

### PR DESCRIPTION
**Pull request by slimepointe**
let user choose how many processes they want to run, also tell them what the output of `crossystem wpsw_cur` even means.
also remove useless things (just dont clear terminal...)

### CODE REVIEW

**Comment by chrossystem** [comment]
Kill yourself

**Comment by slimepointe** [comment]
read the code, its a good pr, you just dont know how to code, have fun with your skid group LOL

**Comment by chrossystem** [comment]
:3

**Comment by slimepointe** [comment]
i know more shit than y'all, have fun though 🤓

**Comment by chrossystem** [comment]
and I have your home IP

**Comment by slimepointe** [comment]
ohhh mrs scary over here!!!!

**Comment by chrossystem** [comment]
okay

**Comment by kxtzownsu** [comment]
both of you are so pressed for no reason

**Comment by chrossystem** [comment]
lmao

**Comment by slimepointe** [comment]
> both of you are so pressed for no reason

i'm not pressed, this is a good pr and she told me to kill myself for no reason

**Comment by slimepointe** [comment]
the pr is good, i never said anything rude in this other than calling them a skid

**Comment by chrossystem** [comment]
he recommended stuff we already had in the script, it just hasn't been updated yet

**Comment by slimepointe** [comment]
> he recommended stuff we already had in the script, it just hasn't been updated yet

so push the pr ..? basically i made the script better before y'all did 🤦‍♂️

**Comment by chrossystem** [comment]
we had already made it better, we didn't want to push something this late though

**Comment by slimepointe** [comment]
you didnt even review the pr, you posted me in the readme hating on my fork (which was for a pr to make it better...?) right after i made it, then replied to my pr hating on me for no reason even though its a good pr

**Comment by chrossystem** [comment]
as i said, we already had those changes

**Comment by slimepointe** [comment]
> you posted me in the readme hating on my fork (which was for a pr to make it better...?) right after i made it

**Comment by chrossystem** [comment]
yeah why wouldn't i
the entire time you've been in whelement you've just been an annoying asshole
hell, we were practically forced to let you in

**Comment by slimepointe** [comment]
yeah pretty dumb to let me in, gave me alot of great info on an rma unlock, 90% of the way done to just generating the auth code 😄

**Comment by chrossystem** [comment]
lying again?

**Comment by slimepointe** [comment]
not lying, the h1_chip.pdf gave me basically everything i need to know, server keys are sitting out on an unsecured server and you can easily get device keys

**Comment by chrossystem** [comment]
no it doesnt lmfaooooo

**Comment by slimepointe** [comment]
yeah it does but ok

**Comment by chrossystem** [comment]
alright then, get me an auth code

**Comment by slimepointe** [comment]
ok reason with me WHY i would help you?

**Comment by chrossystem** [comment]
"i can get an rma auth code"
"prove it"
"oh but i cant show you"
:sob:

**Comment by slimepointe** [comment]
LMFAOOOO renaming it to shit changes when you admitted to them being what you were already going to add is CRAZYY

**Comment by TheSpiritOfDark** [comment]
Whelement members try to have an actual discussion challenge (impossible)

**Comment by MunyDev** [comment]
i usually have non-owners handle prs for this exact reason

**Comment by TheSpiritOfDark** [comment]
Yeah, crossystem did a very poor job with this, ill confront her once she wakes up

**Pull request closed without merging**
